### ISSUE TITLE
Ability to modify the default dokuwiki theme for other plugins

### ISSUE THREAD

**Issue by divadsn** [dokuwiki/docker#10]
First of all, big thanks for an official docker image, I always like when developers make their official images themselves.

I wanted to setup the Translation plugin, but that requires modifying the `sidebarheader.html` file in the default dokuwiki theme to show a dropdown with available translations on the sidebar.

However, that one is symlinked to a directory within the container at startup:

![image](https://github.com/user-attachments/assets/f590f86f-ec48-4edf-bc5c-341137e2f193)

I thought of potentially removing the symlink and placing the default theme, but will that not break the container?

**Comment by splitbrain** [comment]
First of all, the trranslation plugin can also be integrated into the sidebar via syntax.

Second: includes for the includehooks can also be placed into the conf folder. No need to access the template dir.
