### ISSUE TITLE
Loading php-ldap module

### ISSUE THREAD

**Issue by crossrider00** [dokuwiki/docker#12]
Is there a way to get php's ldap module working? I tried activating it as suggested in the readme by putting a php.ini in the storage folder with

  extension=ldap

inside. However, php will instantly complain it can't find the module.

Did I miss anything or is it just not included?

**Comment by splitbrain** [comment]
Yeah the container doesn't have the ldap module. Might be a good idea to add it. If you're using AD, I would recommend the pureldap plugin instead.
