### ISSUE TITLE
Running dokuwiki using podman - solved

### ISSUE THREAD

**Issue by bartland** [dokuwiki/docker#13]
I recently updated a 5 year old dokuwiki running in docker to Kaos. Update went amazingly smoothly, so THANK YOU. 

Then I decided to strip docker off my system and install podman. 
```
$ cat /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20240813"
```

The dokuwiki container internally uses uid:gid 1001:127. 

> $ podman exec -it dokuwiki  bash
1001@9a226488fcdc:~$ pwd
/var/www/html
1001@9a226488fcdc:~$ ls -l
total 88
-rw-r--r-- 1 1001 127  18092 Aug  5 06:28 COPYING
-rw-r--r-- 1 1001 127    308 Aug  5 06:28 README
-rw-r--r-- 1 1001 127    862 Aug  5 06:28 SECURITY.md
-rw-r--r-- 1 1001 127     19 Aug  5 06:28 VERSION
drwxr-xr-x 1 1001 127    160 Aug  5 06:28 bin
lrwxrwxrwx 1 root root    13 Aug 17 01:42 conf -> /storage/conf
drwxr-xr-x 1 1001 127   4096 Aug  5 06:28 conf.core
lrwxrwxrwx 1 root root    13 Aug 17 01:42 data -> /storage/data
drwxr-xr-x 1 1001 127   4096 Aug  5 06:28 data.core
-rw-r--r-- 1 1001 127   3651 Aug  5 06:28 doku.php
-rw-r--r-- 1 1001 127   2034 Aug  5 06:28 feed.php
-rw-r--r-- 1 root root   684 Aug 14 01:45 health.php
drwxr-xr-x 1 1001 127   4096 Aug  5 06:28 inc
-rw-r--r-- 1 1001 127   2529 Aug  5 06:28 index.php
-rw-r--r-- 1 1001 127  21176 Aug  5 06:28 install.php
drwxr-xr-x 1 1001 127    140 Aug 17 01:42 lib
drwxr-xr-x 1 1001 127   4096 Aug  5 06:28 vendor
1001@9a226488fcdc:~$ 

My account is 1000:100 and I had various "Permission denied" or "directory is not writable" errors but was finally able to get it working with:

`podman run -d --name=dokuwiki --userns keep-id:uid=1001,gid=127 -p 8080:8080 -v $HOME/data/dokuwiki/mywiki:/storage:z dokuwiki/dokuwiki:stable`

The key was mapping the internal ids to my user ids
`--userns keep-id:uid=1001,gid=127`

The :z (or :Z) seems to be optional.

(Thanks for an outstanding tool.)

**Comment by gagzzz** [comment]
For what it's worth and since i found this when looking for info regarding dokuwiki in podman, i run a bunch of dokuwiki containers in rootless podman, and i sometimes need to user `podman unshare chown -R 33:33 dokuwiki/` for example when i migrate a blog from a server to another.
