### ISSUE TITLE
Extensions permissions are not set up correctly in image

### ISSUE THREAD

**Issue by Alexxor36** [dokuwiki/docker#17]
I have an issue running the dokuwiki container - https://github.com/dokuwiki/docker
It runs smoothly when I run it per their instructions:

docker run -p 8080:8080 --user 1000:1000 -v /home/name/dokuwiki/:/storage dokuwiki/dokuwiki:stable

However, I get a permissions error for their extensions.
"Extension directory is not writeable"

note that /var/www is owned by root and is 755 inside the docker container, but cannot change it ("operation not permitted" error)
I tried to temporarily make the volume it maps to on the host (/user/<name>/dukiwiki/lib) 777 and that still didn't fix the problem
ie, this doesn't solve the problem (with chmod 777):
https://forum.dokuwiki.org/d/12981-extension-directory-is-not-writable

and this won't work inside the container:
(source: https://loganmarchione.com/2022/03/the-best-way-to-run-dokuwiki-in-docker/ )

**Comment by splitbrain** [comment]
sorry, this report is a mess. all kinds of mixed signals here. it's not clear what uid/gid your mapped volume has (not even where it is located) you also mention an article that has nothing to do with this image.

the image works fine for lots of people, so I have to assume you're running it wrong and will close this issue (I can not provide docker support in addition to dokuwiki support). feel free to open a new issue if you have a clearly described, reproducible setup.
