### ISSUE TITLE
Permissions incorrectly set

### ISSUE THREAD

**Issue by Alexxor36** [dokuwiki/docker#18]
Let's try again.

Reproducible error:

1. Install and run docuwiki container per instructions on github; map storage to folder in username home folder (UID 1000)
2. Run installer script; [ensure "ACL" is on]
3. When attempting to install extensions, error appears "Extension directory is not writeable"

**Comment by Michaelsy** [comment]
> **This setup ensures that all adjustments you may make via the Admin interface will be stored correctly in the storage volume** while all bundled data is kept in the container and is correctly updated/replaced when the container is updated.

This means that your access rights to the storage volume are not set correctly.

\- Michael Sy.

**Comment by splitbrain** [comment]
I added more info on permissions to the README
