### ISSUE TITLE
Add more plugins to image

### ISSUE THREAD

**Issue by ChaosKid42** [dokuwiki/docker#23]
Hi @splitbrain!
First of all let me thank you for this docker image and the great software dokuwiki itself.
I want to extend your image by adding more DokuWiki-plugins to the image. I plan to pass a list of plugin-ids to the Dockerfile and then download and install the plugins at image build-time.
My question:
Is there any easy way to download and install a bunch of plugins, e.g. by calling certain php-functions inside the container? Otherwise I would just use a shellscript that parses the plugin-pages, gets the download link, downloads and unpacks the archive. But this does not seem to be very robust to me as the plugin repo might change in the future and the php-code includes the logic to access the plugin repo anyway.

**Comment by splitbrain** [comment]
The extension manager has a CLI interface.
