### ISSUE TITLE
Dokuwiki migration question

### ISSUE THREAD

**Issue by vasqueeg** [dokuwiki/docker#7]
Hello Team,

Good day!

I am planning to migrate our existing dokuwiki from Binary installation into container.  I wonder if this supports authentication like OpenLDAP?  If yes, is there somewhere in the configuration file(s) that I can enable it?  Also, do you have a tool that I can use to migrate my existing dokuwiki pages to the dokuwiki container?

Thank you in advance!

./ed

**Comment by splitbrain** [comment]
Sorry, usage questions are better suited for the [forum](https://forum.dokuwiki.org). The issue tracker is reserved for bugs and feature requests.
